Task 12 6
AdamPawlinski/task-12-6 pull request #1
Opened 2018-03-25 10:18 UTC by AdamPawlinski

Finish task. Ask for acceptance.

2018-03-25 20:51 UTC, matwjablonski requested changes

2018-03-25 20:51 UTC, matwjablonski commented on js/script.js
> +var url = 'https://restcountries.eu/rest/v2/name/';
at first check that DOM is loaded

2018-03-25 20:51 UTC, matwjablonski commented on js/script.js
> +  if(!countryName.length) countryName = 'Poland';
add space after `if`

2018-03-27 04:51 UTC, AdamPawlinski commented
bugs fixed. Ask for acceptance.

2018-03-27 07:12 UTC, matwjablonski approved these changes

2018-09-12 04:36 UTC, merged